export const rowNames = {
  st: "Selected tab",
  virusType: "Virus type",
  occupancyCategory: "Occupancy category",
  selectedSubcategory: "Subccategories",
    floorArea: "Floor area (sqft)",
    height: "Height (ft)",
    occupantNumber: "Occupant number",
    occupiedPeriod: "Occupied period (min)",
    supplyAir: "Supply air (cfm)",
    outdoorAir: "Outdoor air (cfm)",
    filter: "Filter efficiency",
    hvacUV: "UVC inactivation (%)",
    hvacTreatment: "Air treatment ECAi (cfm)",
    roomAC: "Air cleaner ECAi (cfm)",
    roomUV: "In-room UV ECAi (cfm)",
    roomTreatment: "Air treatment device ECAi (cfm)",
    maskInfector: "Mask efficiency - infector (%)",
    maskSus: "Mask efficiency - susceptible (%)",
    totalCADR: "Total ECAi (cfm)",
    ASHRAE: "ASHRAE 241",
    LANCET1: "LANCET - Equivalent air change rate",
    LANCET2: "LANCET - Number of occupants",
    LANCET3: "LANCET - Floor area + min ASHRAE",
    LANCET4: "LANCET - Secondary attack rate",
    IR: "Individual risk (%)",
    AR: "Aboslute risk (%)",
    E: "Estimated infected people",
    R: "Reproduction number",
    drisk: "Risk by distance (%)",
    distance: "Distance (ft)"

  };